#ifndef CONSTANT
#define CONSTANT

#define NANO_BUFFER 32
#define TINY_BUFFER 64
#define SMALL_BUFFER 128
#define MEDIUM_BUFFER 256
#define BIG_BUFFER 512
#define HUGE_BUFFER 1024


#define SHOW_DATABASES 0
#define SHOW_TABLES 1

#define MAX_TABLE_ATTRIBUTES 64


#define METADATA_TABLES_PATH "\\.tables"

#define FLAG_AUTO_INCREMENT "AUTO_INCREMENT"
#define FLAG_NOT_NULL "NOT NULL"
#define FLAG_PK "PRIMARY KEY"


#define UNKNOW_DB "UNKNOW"


#define FAILED_AT_INIT -1

// NAME;TYPE;SIZE;PK?;NN?;AI;UNQ;FK?;
#define TABLE_INDEX_NAME 0
#define TABLE_INDEX_TYPE 1
#define TABLE_INDEX_SIZE 2
#define TABLE_INDEX_PK 3
#define TABLE_INDEX_NN 4
#define TABLE_INDEX_AI 5
#define TABLE_INDEX_UNQ 6
#define TABLE_INDEX_FK 7



#endif